language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_cache:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo install -f cargo-tarpaulin
    fi
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
      echo "Uploaded code coverage"
    fi