[package]
name = "august-offensive"
version = "0.1.0"
authors = ["Kevin J Hoerr <kjhoerr@submelon.tech>"]
description = "Turn-based strategy game as a web service"
license = "ISC"
readme = "README.md"
repository = "https://gitlab.com/kjhoerr/august-offensive.git"

[dependencies]
dotenv = "0.10"
env_logger = "0.5"
error-chain = "^0.12"

diesel = { version = "1.3.0", features = ["postgres"] }

actix = "0.7"
actix-web = "^0.7"